language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="PlayRtttl Arduino Library"
before_install:
# Workaround for avoiding "fork/exec /bin/xtensa-lx106-elf-g++: no such file or directory"
- echo "Removing ESP8266 cache"
- rm -rf ~/.arduino15/packages/esp8266
- source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
- build_platform uno
- build_platform leonardo
- build_platform mega2560
- build_platform esp32
- build_platform esp8266
- build_platform cplayClassic
notifications:
  email:
    recipients:
      - armin.arduino@gmail.com
    on_success: always
    on_failure: always
