language: c
sudo: true
cache:
   directories:
   - ~/arduino_ide
   - ~/.arduino15/packages/
git:
   depth: false
   quiet: true
env:
   global:
   - PRETTYNAME="PlayRtttl Arduino Library"
   - INSTALL_PLATFORMS="avr,esp8266,esp32,stm32"
before_install:
- source <(curl -SLs https://raw.githubusercontent.com/ArminJo/travis-ci-arduino/master/install.sh)
install:
- arduino --install-library "Talkie","EasyButtonAtInt01"
script:
- build_platform uno
- build_platform leonardo
- build_platform mega2560
- build_platform esp32
- build_platform esp8266
- build_platform cplayClassic
notifications:
   email:
      recipients:
      - armin.arduino@gmail.com
      on_success: always
      on_failure: always